version: '3.7'

services:
  app:
    build: ./app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - JAEGER_AGENT_HOST=jaeger
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/index:/loki/index
      - ./loki-data/wal:/loki/wal

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - "6831:6831/udp"
      - "16686:16686"

volumes:
  grafana-storage:
    
